(function(global){'use strict';
const STORAGE_V5='profitRiskDataV5',STORAGE_V4='profitRiskDataV4';
const DEFAULT_STORE={version:5,config:{capital:2000,goalPct:2.5,stopPct:3,riskPct:.75,maxTrades:8,maxLosses:3,goalAmount:0},trades:[],withdrawals:[],warren:{transactions:[],summary:null,meta:{fileName:'',importedAt:'',periodStart:'',periodEnd:'',movementCount:0}},meta:{fileName:'',importedAt:'',period:'',integrity:'—',mismatches:0}};
const clone=o=>JSON.parse(JSON.stringify(o));
function migrate(old){const n=clone(DEFAULT_STORE);if(!old||typeof old!=='object')return n;n.config=Object.assign(n.config,old.config||{});n.trades=Array.isArray(old.trades)?old.trades:[];n.withdrawals=Array.isArray(old.withdrawals)?old.withdrawals:[];n.meta=Object.assign(n.meta,old.meta||{});if(old.warren)n.warren=Object.assign(n.warren,old.warren,{meta:Object.assign(n.warren.meta,(old.warren||{}).meta||{})});return n}
function load(){try{const v5=JSON.parse(localStorage.getItem(STORAGE_V5)||'null');if(v5)return migrate(v5)}catch{}try{const v4=JSON.parse(localStorage.getItem(STORAGE_V4)||'null');if(v4){const m=migrate(v4);save(m);return m}}catch{}return clone(DEFAULT_STORE)}
function save(store){store.version=5;localStorage.setItem(STORAGE_V5,JSON.stringify(store));return store}function reset(){localStorage.removeItem(STORAGE_V5);return clone(DEFAULT_STORE)}
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number.isFinite(+n)?+n:0),pct=n=>`${(Number.isFinite(+n)?+n:0).toFixed(1).replace('.',',')}%`,norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/R\$/gi,'').replace(/\s/g,'');if(!s||s==='-')return 0;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(','))s=s.replace(',','.');const n=Number(s.replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:0}
function isoFromBR(d){const m=String(d||'').match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:''}function fmtDate(d){if(!d)return'—';const[y,m,x]=d.split('-');return`${x}/${m}/${y}`}function fmtTooltipDate(d){const m=String(d||'').match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!m)return d;const date=new Date(Date.UTC(+m[3],+m[2]-1,+m[1]));if(date.getUTCFullYear()!==+m[3]||date.getUTCMonth()!==+m[2]-1||date.getUTCDate()!==+m[1])return d;const weekday=new Intl.DateTimeFormat('pt-BR',{weekday:'short',timeZone:'UTC'}).format(date).replace('.','');return`${weekday.charAt(0).toUpperCase()+weekday.slice(1)}, ${d}`}
function openDate(v){const m=String(v??'').trim().match(/^(\d{2})\/(\d{2})\/(\d{4})\s+(\d{1,2}):(\d{2})(?::(\d{2}))?/);return m?{date:`${m[3]}-${m[2]}-${m[1]}`,time:`${String(+m[4]).padStart(2,'0')}:${m[5]}:${m[6]||'00'}`,stamp:`${m[3]}-${m[2]}-${m[1]}T${String(+m[4]).padStart(2,'0')}:${m[5]}:${m[6]||'00'}`}:{date:'',time:'',stamp:''}}
function csvRows(text){const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const sem=(lines[0].match(/;/g)||[]).length,com=(lines[0].match(/,/g)||[]).length,tab=(lines[0].match(/\t/g)||[]).length,del=tab>sem&&tab>com?'\t':sem>=com?';':',';return lines.map(line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===del&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out})}
function parseProfit(rows){const hi=rows.findIndex(r=>{const n=(r||[]).map(norm);return n.includes('ativo')&&n.includes('abertura')&&n.includes('fechamento')&&n.includes('resoperacao')&&n.includes('total')});if(hi<0)throw Error('Tabela de operações do Profit não encontrada.');const map={};rows[hi].forEach((x,i)=>{const k=norm(x);if(map[k]===undefined)map[k]=i});for(const k of['ativo','abertura','fechamento','qtdcompra','qtdvenda','lado','precocompra','precovenda','resoperacao','total'])if(map[k]===undefined)throw Error('Coluna obrigatória não encontrada: '+k);let cum=0,mis=0,trades=[];for(let i=hi+1;i<rows.length;i++){const r=rows[i]||[],o=openDate(r[map.abertura]),f=openDate(r[map.fechamento]);if(!o.date)continue;const side=String(r[map.lado]??'').trim().toUpperCase(),buy=num(r[map.precocompra]),sell=num(r[map.precovenda]),result=num(r[map.resoperacao]),total=num(r[map.total]),qty=Math.max(num(r[map.qtdcompra]),num(r[map.qtdvenda]));cum+=result;if(Math.abs(cum-total)>.011)mis++;trades.push({id:`p-${o.stamp}-${i}`,asset:String(r[map.ativo]??'N/A').trim().toUpperCase(),date:o.date,open:o.time,close:f.time,stamp:o.stamp,side,qty,entry:side==='V'?sell:buy,exit:side==='V'?buy:sell,result,total})}if(!trades.length)throw Error('Nenhuma operação válida encontrada.');trades.sort((a,b)=>a.stamp.localeCompare(b.stamp));return{trades,mis}}
async function readProfitFile(file){if(!/\.csv$/i.test(file.name))throw Error('Nesta versão online, use o relatório do Profit em CSV.');const b=await file.arrayBuffer();let text=new TextDecoder('utf-8').decode(b);if((text.match(/�/g)||[]).length>2)text=new TextDecoder('windows-1252').decode(b);return parseProfit(csvRows(text))}
function dayStats(list){const m={};(list||[]).forEach(t=>{const d=m[t.date]||(m[t.date]={date:t.date,result:0,count:0,wins:0,losses:0,peak:0,worst:0,run:0});d.result+=+t.result||0;d.count++;if(t.result>0)d.wins++;if(t.result<0)d.losses++;d.run+=+t.result||0;d.peak=Math.max(d.peak,d.run);d.worst=Math.min(d.worst,d.run)});return Object.values(m).sort((a,b)=>a.date.localeCompare(b.date))}
function tradeMetrics(list,capital=0){const trades=list||[],net=trades.reduce((a,t)=>a+(+t.result||0),0),wins=trades.filter(t=>t.result>0),losses=trades.filter(t=>t.result<0),gp=wins.reduce((a,t)=>a+t.result,0),gl=Math.abs(losses.reduce((a,t)=>a+t.result,0)),pf=gl?gp/gl:gp>0?Infinity:0,avgWin=wins.length?gp/wins.length:0,avgLoss=losses.length?gl/losses.length:0,payoff=avgLoss?avgWin/avgLoss:avgWin?Infinity:0;let eq=capital,peak=eq,maxDD=0,streak=0,cur=0;trades.forEach(t=>{eq+=t.result;peak=Math.max(peak,eq);maxDD=Math.max(maxDD,peak-eq);if(t.result<0){cur++;streak=Math.max(streak,cur)}else if(t.result>0)cur=0});const days=dayStats(trades),pos=days.filter(d=>d.result>0).length;return{net,wins,losses,gp,gl,pf,payoff,avg:trades.length?net/trades.length:0,maxDD,streak,days,posPct:days.length?100*pos/days.length:0,avgWin,avgLoss}}
function mergeWithdrawals(store){const arr=[];for(const w of(store.withdrawals||[]))arr.push({id:w.id||`m-${w.date}-${w.value}`,date:w.date,value:+w.value||0,note:w.note||'Lançamento manual',source:'manual'});for(const t of(((store.warren||{}).transactions)||[]))if(t.category==='withdrawal')arr.push({id:t.id,date:t.date,value:Math.abs(t.value),note:t.description,source:'Warren'});const out=[],seen=new Set();for(const w of arr.sort((a,b)=>a.date.localeCompare(b.date))){const key=`${w.date}|${(+w.value).toFixed(2)}`;if(seen.has(key)&&w.source==='manual')continue;seen.add(key);out.push(w)}return out}
function financial(store){const globalNet=(store.trades||[]).reduce((a,t)=>a+(+t.result||0),0),withdrawals=mergeWithdrawals(store),withdrawTotal=withdrawals.reduce((a,w)=>a+w.value,0),wtx=((store.warren||{}).transactions||[]),deposits=wtx.filter(t=>t.category==='deposit').reduce((a,t)=>a+Math.abs(t.value),0),fees=wtx.filter(t=>['fee_registration','fee_emoluments','irrf','platform'].includes(t.category)).reduce((a,t)=>a+Math.abs(t.value),0),daytradeAdj=wtx.filter(t=>t.category==='daytrade').reduce((a,t)=>a+t.value,0),wSummary=(store.warren||{}).summary,projected=(+store.config.capital||0)+globalNet-withdrawTotal;let real=projected,summaryIntegrity='sem-extrato',summaryComputed=null;if(wSummary&&wtx.length){const initial=+wSummary.initial||0,entries=Math.abs(+wSummary.entries||0),exits=Math.abs(+wSummary.exits||0),declared=+wSummary.final||0;summaryComputed=initial+entries-exits;const tolerance=Math.max(.05,Math.abs(summaryComputed)*.001);if(Number.isFinite(declared)&&Math.abs(declared-summaryComputed)<=tolerance){real=declared;summaryIntegrity='confirmado'}else if(Number.isFinite(summaryComputed)){real=summaryComputed;summaryIntegrity='recalculado'}}return{globalNet,withdrawals,withdrawTotal,deposits,fees,daytradeAdj,projected,real,wSummary,summaryIntegrity,summaryComputed}}
function aggregate(list,keyFn){const m={};(list||[]).forEach((t,i)=>{const k=keyFn(t,i)||'N/A';m[k]=(m[k]||0)+(+t.result||0)});return Object.entries(m).sort((a,b)=>String(a[0]).localeCompare(String(b[0]),undefined,{numeric:true}))}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function onlineLink(page){return`https://htmlpreview.github.io/?https://github.com/RealPedroSantos/shell-master/blob/deploy-profit-risk-daytrade/profit-risk-daytrade/${page}`}function fixLinks(){if(location.hostname==='htmlpreview.github.io')document.querySelectorAll('[data-page]').forEach(a=>a.href=onlineLink(a.dataset.page))}
global.PR={STORAGE_V5,DEFAULT_STORE,load,save,reset,money,pct,norm,num,fmtDate,fmtTooltipDate,isoFromBR,readProfitFile,parseProfit,csvRows,dayStats,tradeMetrics,mergeWithdrawals,financial,aggregate,esc,fixLinks,onlineLink};
})(window);
