(()=>{'use strict';PR.fixLinks();let store=PR.load();const $=s=>document.querySelector(s),setStatus=(id,text,type='')=>{const e=$(id);e.textContent=text;e.className='status-pill'+(type?' '+type:'')};
function brInput(n){return Number.isFinite(+n)?(+n).toFixed(2).replace('.',','):''}
function cfgToUI(){const c=store.config;$('#capital').value=brInput(c.capital);$('#goalAmount').value=c.goalAmount?brInput(c.goalAmount):'';$('#goalPct').value=String(c.goalPct).replace('.',',');$('#stopPct').value=String(c.stopPct).replace('.',',');$('#riskPct').value=String(c.riskPct).replace('.',',');$('#maxTrades').value=c.maxTrades;$('#maxLosses').value=c.maxLosses}
function uiToCfg(){store.config.capital=Math.max(.01,PR.num($('#capital').value));store.config.goalAmount=Math.max(0,PR.num($('#goalAmount').value));store.config.goalPct=Math.max(0,PR.num($('#goalPct').value));store.config.stopPct=Math.max(.01,PR.num($('#stopPct').value));store.config.riskPct=Math.max(.01,PR.num($('#riskPct').value));store.config.maxTrades=Math.max(1,+$('#maxTrades').value||1);store.config.maxLosses=Math.max(1,+$('#maxLosses').value||1);PR.save(store);render()}
function renderMeta(){const t=store.trades||[],w=store.warren||{},wm=w.meta||{};$('#tradeCount').textContent=t.length.toLocaleString('pt-BR');$('#movementCount').textContent=((w.transactions||[]).length).toLocaleString('pt-BR');$('#profitMeta').textContent=store.meta.fileName?(store.meta.fileName+' • '+(store.meta.integrity||'')):'Não importado';$('#warrenMeta').textContent=wm.fileName?(wm.fileName+' • salvo'):'Não importado';$('#profitPeriod').textContent=t.length?`${PR.fmtDate(t[0].date)} → ${PR.fmtDate(t.at(-1).date)}`:'—';$('#warrenPeriod').textContent=wm.periodStart?`${PR.fmtDate(wm.periodStart)} → ${PR.fmtDate(wm.periodEnd)}`:'—';const s=w.summary;if(s&&((w.transactions||[]).length)){ $('#wInitial').textContent=PR.money(s.initial);$('#wEntries').textContent=PR.money(s.entries);$('#wExits').textContent='-'+PR.money(Math.abs(s.exits)).replace('R$ ','R$ ');$('#wFinal').textContent=PR.money(s.final)}else{$('#wInitial').textContent=$('#wEntries').textContent=$('#wExits').textContent=$('#wFinal').textContent='—'} }
function renderWithdrawals(){const arr=PR.mergeWithdrawals(store);$('#withdrawRows').innerHTML=arr.length?[...arr].reverse().map(w=>`<tr><td>${PR.fmtDate(w.date)}</td><td class="warn"><strong>${PR.money(w.value)}</strong></td><td>${PR.esc(w.source)}</td><td>${PR.esc(w.note)}</td></tr>`).join(''):'<tr><td colspan="4"><div class="chart-empty" style="height:80px">Nenhum saque registrado.</div></td></tr>'}
function renderRecon(){const rows=PR.reconciliation(store),hasP=(store.trades||[]).length,hasW=((store.warren||{}).transactions||[]).length;if(!hasP||!hasW){setStatus('#reconStatus','Aguardando dois arquivos');$('#reconRows').innerHTML='<tr><td colspan="8"><div class="chart-empty" style="height:90px">Importe o relatório Profit e o extrato Warren para conciliar.</div></td></tr>';return}const ok=rows.filter(r=>r.status==='ok').length,div=rows.filter(r=>r.status==='divergente').length;setStatus('#reconStatus',`${ok} conciliados${div?` • ${div} divergências`:''}`,div?'bad':'good');$('#reconRows').innerHTML=[...rows].reverse().map(r=>`<tr><td>${PR.fmtDate(r.date)}</td><td class="${r.profit>=0?'pos':'neg'}">${PR.money(r.profit)}</td><td class="${r.adj>=0?'pos':'neg'}">${PR.money(r.adj)}</td><td class="neg">${PR.money(r.fees)}</td><td class="neg">${PR.money(r.irrf)}</td><td class="${r.netWarren>=0?'pos':'neg'}"><strong>${PR.money(r.netWarren)}</strong></td><td class="${Math.abs(r.diff)>.011?'neg':''}">${PR.money(r.diff)}</td><td>${r.status==='ok'?'<span class="pos">Conciliado</span>':r.status==='sem-warren'?'<span class="warn">Sem ajuste Warren</span>':'<span class="neg">Divergente</span>'}</td></tr>`).join('')}
function render(){renderMeta();renderWithdrawals();renderRecon();const hasP=(store.trades||[]).length,hasW=((store.warren||{}).transactions||[]).length;if(hasP)setStatus('#profitStatus','Importado','good');else setStatus('#profitStatus','Aguardando');if(hasW)setStatus('#warrenStatus','Importado','good');else setStatus('#warrenStatus','Aguardando')}
async function importProfit(file){setStatus('#profitStatus','Processando');$('#profitMsg').className='notice';$('#profitMsg').textContent='Lendo relatório...';try{const r=await PR.readProfitFile(file);store.trades=r.trades;store.meta={fileName:file.name,importedAt:new Date().toISOString(),period:`${r.trades[0].date}|${r.trades.at(-1).date}`,integrity:r.mis?'Divergências':'OK',mismatches:r.mis};PR.save(store);$('#profitMsg').className='notice good';$('#profitMsg').textContent=`${r.trades.length} operações importadas. Integridade ${r.mis?'com divergências':'OK'}.`;render()}catch(e){setStatus('#profitStatus','Erro','bad');$('#profitMsg').className='notice bad';$('#profitMsg').textContent=e.message}}
async function importWarren(file){setStatus('#warrenStatus','Processando');$('#warrenMsg').className='notice';$('#warrenMsg').textContent='Lendo e classificando o PDF...';try{const r=await PR.readWarrenPdf(file);store.warren={transactions:r.transactions,summary:r.summary,meta:{fileName:file.name,importedAt:new Date().toISOString(),periodStart:r.periodStart,periodEnd:r.periodEnd,movementCount:r.transactions.length}};PR.save(store);$('#warrenMsg').className='notice good';$('#warrenMsg').textContent=`${r.transactions.length} movimentações reconhecidas. Saldo final: ${PR.money(r.summary.final)}.`;render()}catch(e){setStatus('#warrenStatus','Erro','bad');$('#warrenMsg').className='notice bad';$('#warrenMsg').textContent=e.message}}
$('#profitFile').addEventListener('change',e=>e.target.files[0]&&importProfit(e.target.files[0]));$('#warrenFile').addEventListener('change',e=>e.target.files[0]&&importWarren(e.target.files[0]));
function dropWire(zone,input,fn){const z=$(zone);['dragenter','dragover'].forEach(ev=>z.addEventListener(ev,e=>{e.preventDefault();z.classList.add('drag')}));['dragleave','drop'].forEach(ev=>z.addEventListener(ev,e=>{e.preventDefault();z.classList.remove('drag')}));z.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f)fn(f)})}dropWire('#profitDrop','#profitFile',importProfit);dropWire('#warrenDrop','#warrenFile',importWarren);
['capital','goalAmount','goalPct','stopPct','riskPct','maxTrades','maxLosses'].forEach(id=>$('#'+id).addEventListener('change',uiToCfg));
$('#withdrawForm').addEventListener('submit',e=>{e.preventDefault();const date=$('#withdrawDate').value,value=Math.abs(PR.num($('#withdrawValue').value));if(!date||!value)return;store.withdrawals.push({id:`m-${Date.now()}`,date,value,note:$('#withdrawNote').value.trim()||'Saque manual'});PR.save(store);$('#withdrawValue').value='';$('#withdrawNote').value='';$('#withdrawMsg').className='notice good';$('#withdrawMsg').textContent='Saque manual salvo.';render()});
$('#clearManualWithdrawals').onclick=()=>{if(confirm('Remover todos os saques lançados manualmente?')){store.withdrawals=[];PR.save(store);render()}};$('#clearProfit').onclick=()=>{if(confirm('Remover o relatório Profit salvo?')){store.trades=[];store.meta={fileName:'',importedAt:'',period:'',integrity:'—',mismatches:0};PR.save(store);render()}};$('#clearWarren').onclick=()=>{if(confirm('Remover o extrato Warren salvo?')){store.warren={transactions:[],summary:null,meta:{fileName:'',importedAt:'',periodStart:'',periodEnd:'',movementCount:0}};PR.save(store);render()}};$('#clearAll').onclick=()=>{if(confirm('Apagar todos os dados e configurações?')){store=PR.reset();PR.save(store);cfgToUI();render()}};
cfgToUI();$('#withdrawDate').value=new Date().toISOString().slice(0,10);render();
})();
