(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const views=$$('.view');
if(views.length){views.forEach(v=>v.classList.remove('active'));const d=$('#dashboard');if(d)d.classList.add('active');}
let store;
try{store=window.PR&&PR.load?PR.load():null}catch(e){console.error('Falha ao carregar dados',e)}
if(!store){store={config:{capital:2000,goalAmount:0,goalPct:2.5,stopPct:3,riskPct:.75,maxTrades:8,maxLosses:3},trades:[],withdrawals:[],warren:{transactions:[],summary:null,meta:{}},meta:{}}}
let chartState={hour:'',ordinal:null};
const viewMap={dashboard:'dashboard',data:'data',profitImport:'data',warrenImport:'data',withdrawSection:'data',riskSection:'data',reconciliation:'data'};
function safe(fn){try{return fn()}catch(e){console.error(e);return null}}
function money(n){return window.PR&&PR.money?PR.money(n):new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(+n||0)}
function pct(n){return window.PR&&PR.pct?PR.pct(n):((+n||0).toFixed(1).replace('.',',')+'%')}
function fmt(d){return window.PR&&PR.fmtDate?PR.fmtDate(d):d||'—'}
function show(route='dashboard',push=true){const view=viewMap[route]||'dashboard';views.forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.sidebar [data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route||(route==='dashboard'&&a.dataset.route==='dashboard')||(view==='data'&&route==='data'&&a.dataset.route==='data')));if(push)history.replaceState(null,'','#'+route);if(view==='dashboard')safe(renderDashboard);else safe(renderData);if(view==='data'&&route!=='data')setTimeout(()=>document.getElementById(route)?.scrollIntoView({behavior:'smooth',block:'start'}),60);else window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('click',e=>{const a=e.target.closest('[data-route]');if(!a)return;const r=a.dataset.route;if(!viewMap[r])return;e.preventDefault();show(r,true)});
window.addEventListener('hashchange',()=>show(location.hash.slice(1)||'dashboard',false));
function setMetric(id,val,cls=''){const e=$(id);if(!e)return;e.textContent=val;e.className='metric-value '+cls}
function config(){return store.config||{capital:0,goalAmount:0,goalPct:0,stopPct:0,riskPct:0,maxTrades:8,maxLosses:3}}
function mergedWithdrawals(){if(window.PR&&PR.mergeWithdrawals)return PR.mergeWithdrawals(store);return store.withdrawals||[]}
function financial(){if(window.PR&&PR.financial)return PR.financial(store);const c=config(),net=(store.trades||[]).reduce((a,t)=>a+(+t.result||0),0),w=mergedWithdrawals(),wt=w.reduce((a,x)=>a+(+x.value||0),0);return{globalNet:net,withdrawTotal:wt,projected:(+c.capital||0)+net-wt,real:(+c.capital||0)+net-wt,fees:0,deposits:0,wSummary:store.warren?.summary||null}}
function tradeMetrics(list){if(window.PR&&PR.tradeMetrics)return PR.tradeMetrics(list,+config().capital||0);const wins=list.filter(t=>t.result>0),losses=list.filter(t=>t.result<0),gp=wins.reduce((a,t)=>a+t.result,0),gl=Math.abs(losses.reduce((a,t)=>a+t.result,0)),net=list.reduce((a,t)=>a+t.result,0);return{net,wins,losses,pf:gl?gp/gl:gp?Infinity:0,payoff:0,maxDD:0,days:[],avgWin:wins.length?gp/wins.length:0,avgLoss:losses.length?gl/losses.length:0,streak:0}}
function rebuildFilters(){const t=store.trades||[],a=$('#assetFilter'),q=$('#qtyFilter');if(!a||!q)return;const av=a.value,qv=q.value;a.innerHTML='<option value="">Todos</option>';q.innerHTML='<option value="">Todas</option>';[...new Set(t.map(x=>x.asset))].filter(Boolean).sort().forEach(v=>a.insertAdjacentHTML('beforeend',`<option value="${String(v).replace(/"/g,'&quot;')}">${v}</option>`));[...new Set(t.map(x=>x.qty))].filter(v=>v!==undefined).sort((x,y)=>x-y).forEach(v=>q.insertAdjacentHTML('beforeend',`<option value="${v}">${v}</option>`));if([...a.options].some(o=>o.value===av))a.value=av;if([...q.options].some(o=>o.value===qv))q.value=qv;if(t.length&&!$('#startDate')?.value){$('#startDate').value=t[0].date;$('#endDate').value=t[t.length-1].date}}
function ordinalMap(){const by={};(store.trades||[]).forEach(t=>(by[t.date]||(by[t.date]=[])).push(t));const m=new Map();Object.values(by).forEach(arr=>arr.sort((a,b)=>(a.stamp||'').localeCompare(b.stamp||'')).forEach((t,i)=>m.set(t.id,i+1)));return m}
function filtered(){const t=store.trades||[],s=$('#startDate')?.value||'',e=$('#endDate')?.value||'',a=$('#assetFilter')?.value||'',side=$('#sideFilter')?.value||'',q=$('#qtyFilter')?.value||'',om=chartState.ordinal?ordinalMap():null;return t.filter(x=>(!s||x.date>=s)&&(!e||x.date<=e)&&(!a||x.asset===a)&&(!side||x.side===side)&&(!q||String(x.qty)===q)&&(!chartState.hour||(x.open||'').slice(0,2)+'h'===chartState.hour)&&(!chartState.ordinal||om.get(x.id)===chartState.ordinal))}
function renderBalance(){const f=financial(),c=config(),s=store.warren?.summary,tx=store.warren?.transactions||[];const calc=s?((+s.initial||0)+(+s.entries||0)-Math.abs(+s.exits||0)):null;const validW=!!(s&&tx.length&&Number.isFinite(calc)&&Math.abs(calc-(+s.final||0))<1);const value=validW?(+s.final||0):f.projected;const badge=$('#balanceSource');setMetric('#realBalance',money(value),value>=0?'pos':'neg');if(badge){badge.textContent=validW?'Confirmado pelo extrato Warren':'Estimado pelo sistema';badge.className='balance-source '+(validW?'confirmed':'estimated')}
if(validW){$('#balanceExplain').textContent='Saldo final confirmado pelo último extrato Warren importado.';$('#balanceP1Label').textContent='Saldo inicial Warren';$('#balanceP1').textContent=money(s.initial);$('#balanceP2Label').textContent='Entradas no período';$('#balanceP2').textContent=money(s.entries);$('#balanceP3Label').textContent='Saídas no período';$('#balanceP3').textContent='− '+money(Math.abs(s.exits))}else{$('#balanceExplain').textContent='Estimativa: capital inicial + resultado acumulado − retiradas.';$('#balanceP1Label').textContent='Capital inicial';$('#balanceP1').textContent=money(c.capital);$('#balanceP2Label').textContent='Resultado acumulado';$('#balanceP2').textContent=money(f.globalNet);$('#balanceP3Label').textContent='Retiradas';$('#balanceP3').textContent='− '+money(f.withdrawTotal)}}
function renderChartChips(){const box=$('#activeChartFilters');if(!box)return;const parts=[];if(chartState.hour)parts.push(`<button class="chart-chip" data-clear="hour"><b>Horário</b> ${chartState.hour} ×</button>`);if(chartState.ordinal)parts.push(`<button class="chart-chip" data-clear="ordinal"><b>Trade do dia</b> #${chartState.ordinal} ×</button>`);box.innerHTML=parts.length?'<span class="chart-filter-label">Filtros dos gráficos</span>'+parts.join(''):'';box.classList.toggle('show',!!parts.length);box.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{chartState[b.dataset.clear]=b.dataset.clear==='ordinal'?null:'';renderDashboard()})}
function drawCharts(list,m){if(!(window.PR&&PR.svgBars&&PR.svgLine))return;const c=config(),w=mergedWithdrawals().filter(x=>(!$('#startDate').value||x.date>=$('#startDate').value)&&(!$('#endDate').value||x.date<=$('#endDate').value)).sort((a,b)=>a.date.localeCompare(b.date));let op=+c.capital||0,real=op,labels=['Início'],opData=[op],realData=[real],wi=0;for(const t of list){while(wi<w.length&&w[wi].date<t.date){real-=w[wi].value;labels.push(fmt(w[wi].date));opData.push(op);realData.push(real);wi++}op+=t.result;real+=t.result;labels.push(fmt(t.date));opData.push(op);realData.push(real)}PR.svgLine($('#equityChart'),[{data:opData,color:'#a344df',width:2.3,label:'Capital operacional'},{data:realData,color:'#f56a2d',width:2,label:'Banca após retiradas'}],{labels});PR.svgBars($('#dailyChart'),m.days.map(d=>fmt(d.date)),m.days.map(d=>d.result),{onClick:i=>{const d=m.days[i]?.date;if(d){$('#startDate').value=d;$('#endDate').value=d;renderDashboard()}}});const agg=(key)=>window.PR&&PR.aggregate?PR.aggregate(list,key):[];const h=agg(t=>t.open?t.open.slice(0,2)+'h':'Sem hora');PR.svgBars($('#hourChart'),h.map(x=>x[0]),h.map(x=>x[1]),{onClick:(i,l)=>{chartState.hour=chartState.hour===l?'':l;renderDashboard()}});const side=agg(t=>t.side==='C'?'Compras':t.side==='V'?'Vendas':'N/A');PR.svgBars($('#sideChart'),side.map(x=>x[0]),side.map(x=>x[1]),{onClick:(i,l)=>{$('#sideFilter').value=l==='Compras'?'C':l==='Vendas'?'V':'';renderDashboard()}});const by={};list.forEach(t=>(by[t.date]||(by[t.date]=[])).push(t));const ord={};Object.values(by).forEach(a=>a.sort((x,y)=>(x.stamp||'').localeCompare(y.stamp||'')).forEach((t,i)=>ord[i+1]=(ord[i+1]||0)+t.result));const oa=Object.entries(ord).sort((a,b)=>+a[0]-+b[0]);PR.svgBars($('#ordinalChart'),oa.map(x=>'#'+x[0]),oa.map(x=>x[1]),{onClick:(i,l)=>{const n=+l.replace('#','');chartState.ordinal=chartState.ordinal===n?null:n;renderDashboard()}})}
function renderGoal(){if(!(window.PR&&PR.goalProjection))return;const g=PR.goalProjection(store);if(!g.enabled){$('#goalStatus').textContent='Sem meta';$('#goalAmountView').textContent='—';$('#goalGap').textContent='Configure uma meta em Metas e Riscos.';$('#goalProgressText').textContent='0%';$('#goalProgress').style.width='0%';return}$('#goalStatus').textContent=g.status;$('#goalAmountView').textContent=money(g.goal);$('#goalGap').textContent=g.reached?'Meta alcançada.':`Faltam ${money(g.gap)} para a meta.`;$('#goalProgressText').textContent=pct(g.progress||0);$('#goalProgress').style.width=Math.min(100,g.progress||0)+'%';if($('#medianDays'))$('#medianDays').textContent=g.medianDays==null?'—':g.medianDays+' pregões';if($('#p80Days'))$('#p80Days').textContent=g.p80Days==null?'—':g.p80Days+' pregões';if($('#neededDaily'))$('#neededDaily').textContent=g.netDailyNeeded==null?'—':money(g.netDailyNeeded);if($('#recommendedDaily'))$('#recommendedDaily').textContent=g.recommendedDaily==null?'—':money(g.recommendedDaily);if($('#prob30'))$('#prob30').textContent=pct(g.prob30||0);if($('#prob60'))$('#prob60').textContent=pct(g.prob60||0);if($('#prob90'))$('#prob90').textContent=pct(g.prob90||0);if($('#lossProvision'))$('#lossProvision').textContent=g.totalProvision==null?'—':money(g.totalProvision);if($('#lossRate'))$('#lossRate').textContent=pct(100*(g.lossRate||0));if($('#histDaily'))$('#histDaily').textContent=money(g.mean||0);if($('#goalAdvice')&&PR.goalAdvice)$('#goalAdvice').innerHTML=PR.goalAdvice(store,g).map(([c,t,x])=>`<div class="robot-item ${c}"><strong>${t}</strong>${x}</div>`).join('')}
function renderDashboard(){rebuildFilters();const list=filtered(),m=tradeMetrics(list),t=store.trades||[];renderBalance();setMetric('#net',money(m.net),m.net>0?'pos':m.net<0?'neg':'');setMetric('#pf',list.length?(m.pf===Infinity?'∞':m.pf.toFixed(2).replace('.',',')):'—',m.pf>=1.3?'pos':'');setMetric('#wr',pct(list.length?100*m.wins.length/list.length:0));if($('#wl'))$('#wl').textContent=`${m.wins.length} vencedoras / ${m.losses.length} perdedoras`;setMetric('#payoff',list.length?(m.payoff===Infinity?'∞':(+m.payoff||0).toFixed(2).replace('.',',')):'—');setMetric('#dd',money(m.maxDD),m.maxDD>(+config().capital||0)*.1?'neg':'');if(t.length&&$('#periodTop'))$('#periodTop').textContent=`${fmt(t[0].date)} — ${fmt(t[t.length-1].date)}`;renderChartChips();safe(()=>drawCharts(list,m));safe(renderGoal);if($('#daysRows'))$('#daysRows').innerHTML=m.days?.length?[...m.days].reverse().map(d=>`<tr><td>${fmt(d.date)}</td><td class="${d.result>=0?'pos':'neg'}"><strong>${money(d.result)}</strong></td><td>${d.count}</td><td>${pct(d.count?100*d.wins/d.count:0)}</td><td>${money(d.peak)}</td><td>${money(d.worst)}</td><td>—</td></tr>`).join(''):'<tr><td colspan="7">Sem pregões.</td></tr>';const f=financial();if($('#financialSummary'))$('#financialSummary').innerHTML=[['Capital configurado',money(config().capital)],['Resultado operacional acumulado',money(f.globalNet)],['Custos Warren',money(f.fees||0)],['Aportes Warren',money(f.deposits||0)],['Retiradas',money(f.withdrawTotal)],['Banca estimada',money(f.projected)]].map(r=>`<div class="kpi-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('');if($('#lastProfit'))$('#lastProfit').textContent=store.meta?.importedAt?new Date(store.meta.importedAt).toLocaleString('pt-BR'):'—';if($('#lastWarren'))$('#lastWarren').textContent=store.warren?.meta?.importedAt?new Date(store.warren.meta.importedAt).toLocaleString('pt-BR'):'—';if($('#footerPeriod'))$('#footerPeriod').textContent=t.length?`${fmt(t[0].date)} a ${fmt(t[t.length-1].date)}`:'—';if($('#footerTrades'))$('#footerTrades').textContent=t.length;if($('#footerStatus'))$('#footerStatus').textContent=t.length?'Dados carregados':'Aguardando dados'}
function br(n){return Number.isFinite(+n)?(+n).toFixed(2).replace('.',','):''}
function cfgToUI(){const c=config();if($('#capital'))$('#capital').value=br(c.capital);if($('#goalAmount'))$('#goalAmount').value=c.goalAmount?br(c.goalAmount):'';if($('#goalPct'))$('#goalPct').value=String(c.goalPct||0).replace('.',',');if($('#stopPct'))$('#stopPct').value=String(c.stopPct||0).replace('.',',');if($('#riskPct'))$('#riskPct').value=String(c.riskPct||0).replace('.',',');if($('#maxTrades'))$('#maxTrades').value=c.maxTrades||8;if($('#maxLosses'))$('#maxLosses').value=c.maxLosses||3}
function renderData(){const t=store.trades||[],w=store.warren||{},s=w.summary;if($('#tradeCount'))$('#tradeCount').textContent=t.length;if($('#movementCount'))$('#movementCount').textContent=(w.transactions||[]).length;if($('#profitMeta'))$('#profitMeta').textContent=store.meta?.fileName?store.meta.fileName+' • '+(store.meta.integrity||'OK'):'Não importado';if($('#warrenMeta'))$('#warrenMeta').textContent=w.meta?.fileName?w.meta.fileName:'Não importado';if($('#profitPeriod'))$('#profitPeriod').textContent=t.length?`${fmt(t[0].date)} → ${fmt(t[t.length-1].date)}`:'—';if($('#warrenPeriod'))$('#warrenPeriod').textContent=w.meta?.periodStart?`${fmt(w.meta.periodStart)} → ${fmt(w.meta.periodEnd)}`:'—';if(s){$('#wInitial').textContent=money(s.initial);$('#wEntries').textContent=money(s.entries);$('#wExits').textContent='− '+money(Math.abs(s.exits));$('#wFinal').textContent=money(s.final)}const ws=mergedWithdrawals();if($('#withdrawRows'))$('#withdrawRows').innerHTML=ws.length?[...ws].reverse().map(x=>`<tr><td>${fmt(x.date)}</td><td>${money(x.value)}</td><td>${x.source||'manual'}</td><td>${x.note||''}</td></tr>`).join(''):'<tr><td colspan="4">Nenhum saque registrado.</td></tr>';if(window.PR&&PR.reconciliation&&$('#reconRows')){const r=PR.reconciliation(store);$('#reconRows').innerHTML=r.length?[...r].reverse().map(x=>`<tr><td>${fmt(x.date)}</td><td>${money(x.profit)}</td><td>${money(x.adj)}</td><td>${money(x.fees)}</td><td>${money(x.irrf)}</td><td>${money(x.netWarren)}</td><td>${money(x.diff)}</td><td>${x.status}</td></tr>`).join(''):'<tr><td colspan="8">Importe Profit e Warren para conciliar.</td></tr>'}}
async function importProfit(file){if(!(window.PR&&PR.readProfitFile))return alert('Leitor do Profit não carregado.');try{const r=await PR.readProfitFile(file);store.trades=r.trades;store.meta={fileName:file.name,importedAt:new Date().toISOString(),integrity:r.mis?'Divergências':'OK',mismatches:r.mis};PR.save(store);renderData();renderDashboard()}catch(e){alert(e.message)}}
async function importWarren(file){if(!(window.PR&&PR.readWarrenPdf))return alert('Leitor Warren não carregado.');try{const r=await PR.readWarrenPdf(file);store.warren={transactions:r.transactions,summary:r.summary,meta:{fileName:file.name,importedAt:new Date().toISOString(),periodStart:r.periodStart,periodEnd:r.periodEnd,movementCount:r.transactions.length}};PR.save(store);renderData();renderDashboard()}catch(e){alert(e.message)}}
if($('#profitFile'))$('#profitFile').addEventListener('change',e=>e.target.files[0]&&importProfit(e.target.files[0]));if($('#warrenFile'))$('#warrenFile').addEventListener('change',e=>e.target.files[0]&&importWarren(e.target.files[0]));
['startDate','endDate','assetFilter','sideFilter','qtyFilter'].forEach(id=>$('#'+id)?.addEventListener('change',renderDashboard));if($('#resetFilters'))$('#resetFilters').onclick=()=>{const t=store.trades||[];if(t.length){$('#startDate').value=t[0].date;$('#endDate').value=t[t.length-1].date}$('#assetFilter').value='';$('#sideFilter').value='';$('#qtyFilter').value='';chartState={hour:'',ordinal:null};renderDashboard()};
['capital','goalAmount','goalPct','stopPct','riskPct','maxTrades','maxLosses'].forEach(id=>$('#'+id)?.addEventListener('change',()=>{const c=config();if(id==='capital')c.capital=Math.max(.01,PR.num($('#capital').value));if(id==='goalAmount')c.goalAmount=Math.max(0,PR.num($('#goalAmount').value));if(id==='goalPct')c.goalPct=Math.max(0,PR.num($('#goalPct').value));if(id==='stopPct')c.stopPct=Math.max(.01,PR.num($('#stopPct').value));if(id==='riskPct')c.riskPct=Math.max(.01,PR.num($('#riskPct').value));if(id==='maxTrades')c.maxTrades=Math.max(1,+$('#maxTrades').value||1);if(id==='maxLosses')c.maxLosses=Math.max(1,+$('#maxLosses').value||1);PR.save(store);renderDashboard()}));
if($('#withdrawForm'))$('#withdrawForm').addEventListener('submit',e=>{e.preventDefault();const date=$('#withdrawDate').value,value=Math.abs(PR.num($('#withdrawValue').value));if(!date||!value)return;store.withdrawals=store.withdrawals||[];store.withdrawals.push({id:'m-'+Date.now(),date,value,note:$('#withdrawNote').value||'Saque manual'});PR.save(store);renderData();renderDashboard()});
cfgToUI();if($('#withdrawDate'))$('#withdrawDate').value=new Date().toISOString().slice(0,10);safe(renderData);safe(renderDashboard);show(location.hash.slice(1)||'dashboard',false);
})();