(function(PR,global){'use strict';
const {norm,num,isoFromBR,dayStats}=PR;
function warrenClass(description){const d=norm(description);if(d.includes('ajustedaytradebmf'))return'daytrade';if(d.includes('irrfsobredaytrade'))return'irrf';if(d.includes('taxaderegistrobmf'))return'fee_registration';if(d.includes('taxaemolumentosbmf'))return'fee_emoluments';if(d.includes('cobrancadeprofit'))return'platform';if(d.includes('depositopix')||d.includes('tedrecebida')||d.includes('transferenciarecebida'))return'deposit';if(d.includes('tedenviada')||d.includes('pixenviado')||d.includes('saque'))return'withdrawal';if(d.includes('investimentonofundo'))return'investment_transfer';return'other'}
function transactionTradeDate(description,fallback){const m=String(description||'').match(/(?:dia\s+)?(\d{2}\/\d{2}\/\d{4})/i);return m?isoFromBR(m[1]):fallback}
function parseWarrenText(text){const flat=String(text||'').replace(/\u00a0/g,' ').replace(/\r/g,'\n'),summary={initial:0,entries:0,exits:0,final:0},compact=flat.replace(/[ \t]+/g,' '),findVal=label=>{const re=new RegExp(label+'\\s+(?:Conta\\s+)?(-?R\\$\\s*[\\d.]+,\\d{2})','i'),m=compact.match(re);return m?num(m[1]):0};summary.initial=findVal('Saldo inicial na conta');summary.entries=findVal('Total de entradas');summary.exits=Math.abs(findVal('Total de sa[ií]das'));summary.final=findVal('Saldo final da conta no per[ií]odo');let periodStart='',periodEnd='';const pm=compact.match(/(\d{2}\/\d{2}\/\d{4})\s+[àa]\s+(\d{2}\/\d{2}\/\d{4})/i);if(pm){periodStart=isoFromBR(pm[1]);periodEnd=isoFromBR(pm[2])}let lines=flat.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);const headerIdx=lines.findIndex(l=>/Data.*Movimenta.*Descri.*Valor/i.test(norm(l)));if(headerIdx>=0)lines=lines.slice(headerIdx+1);const tx=[];let pending=[];const isHeader=l=>/^(Extrato de Conta|Data(?: Movimenta[cç][aã]o)?(?: Descri[cç][aã]o)?(?: Valor.*)?|Movimenta[cç][aã]o|Descri[cç][aã]o|Valor \(R\$\)|Resumo do per[ií]odo|Renascen[cç]a|CNPJ|Nome Completo|Banco|Ag[eê]ncia|Conta|CPF|Emiss[aã]o|Per[ií]odo)$/i.test(l)||/^\d{2}$/.test(l)||/^\d{5,8}$/.test(l);for(const line of lines){if(isHeader(line)){if(/^(Extrato de Conta|Data)/i.test(line))pending=[];continue}const dm=line.match(/^(\d{2}\/\d{2}\/\d{4})\b(.*)$/),vals=[...line.matchAll(/-?R\$\s*[\d.]+,\d{2}/g)];if(dm&&vals.length){const date=isoFromBR(dm[1]),valueToken=vals.at(-1)[0],value=num(valueToken),idx=line.lastIndexOf(valueToken);let desc=line.slice(dm[1].length,idx).replace(/\bConta\b/gi,' ').replace(/\s+/g,' ').trim();if(!desc||/^(NC\s*)?\d*$/.test(desc))desc=pending.filter(x=>!isHeader(x)&&!/^\d+$/.test(x)).slice(-2).join(' ').trim();pending=[];if(!desc)continue;const category=warrenClass(desc),tradeDate=transactionTradeDate(desc,date),id=`w-${tx.length}-${date}-${norm(desc)}-${value.toFixed(2)}`;tx.push({id,date,description:desc,value,category,tradeDate});continue}if(!/^[-+]?R\$/.test(line)&&!/^\d+$/.test(line))pending.push(line);if(pending.length>4)pending=pending.slice(-4)}return{transactions:tx,summary,periodStart,periodEnd}}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;s.crossOrigin='anonymous';document.head.appendChild(s)})}
async function ensurePdfJs(){if(global.pdfjsLib)return global.pdfjsLib;const sources=['https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.min.js'];for(const src of sources)try{await loadScript(src);if(global.pdfjsLib){global.pdfjsLib.GlobalWorkerOptions.workerSrc=src.replace('pdf.min.js','pdf.worker.min.js');return global.pdfjsLib}}catch{}throw Error('Não foi possível carregar o leitor de PDF. Tente novamente em uma conexão normal.')}
async function pdfText(file){const lib=await ensurePdfJs(),buf=await file.arrayBuffer(),pdf=await lib.getDocument({data:buf}).promise,pages=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),tc=await page.getTextContent(),items=tc.items.map(i=>({s:i.str,x:i.transform[4],y:i.transform[5]}));const rows=[];items.sort((a,b)=>b.y-a.y||a.x-b.x);for(const it of items){let row=rows.find(r=>Math.abs(r.y-it.y)<2.2);if(!row){row={y:it.y,items:[]};rows.push(row)}row.items.push(it)}rows.sort((a,b)=>b.y-a.y);pages.push(rows.map(r=>r.items.sort((a,b)=>a.x-b.x).map(i=>i.s).join(' ')).join('\n'))}return pages.join('\n')}
async function readWarrenPdf(file){if(!/\.pdf$/i.test(file.name))throw Error('Selecione o extrato consolidado da Warren em PDF.');const parsed=parseWarrenText(await pdfText(file));if(!parsed.transactions.length)throw Error('Nenhuma movimentação da Warren foi reconhecida neste PDF.');return parsed}
function reconciliation(store){const pd={};dayStats(store.trades||[]).forEach(d=>pd[d.date]={profit:d.result,adj:0,costs:0,fees:0,irrf:0});for(const t of((store.warren||{}).transactions||[])){if(!['daytrade','fee_registration','fee_emoluments','irrf'].includes(t.category))continue;const d=t.tradeDate||t.date,o=pd[d]||(pd[d]={profit:0,adj:0,costs:0,fees:0,irrf:0});if(t.category==='daytrade')o.adj+=t.value;else{o.costs+=t.value;if(t.category==='irrf')o.irrf+=Math.abs(t.value);else o.fees+=Math.abs(t.value)}}return Object.entries(pd).map(([date,o])=>({date,...o,netWarren:o.adj+o.costs,diff:o.profit-o.adj,status:Math.abs(o.profit-o.adj)<=.011&&o.adj!==0?'ok':o.adj===0?'sem-warren':'divergente'})).sort((a,b)=>a.date.localeCompare(b.date))}
function dailyNetForProjection(store){const costBy={};reconciliation(store).forEach(r=>costBy[r.date]=r.costs);return dayStats(store.trades||[]).map(d=>({date:d.date,result:d.result+(costBy[d.date]||0)}))}
Object.assign(PR,{readWarrenPdf,parseWarrenText,reconciliation,dailyNetForProjection});
})(window.PR,window);
